// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Q0LB31IXT5WUaVZszBsL2i3w5nKsz_8',
    appId: '1:216697039326:web:552a8d6d0dd2165a88554f',
    messagingSenderId: '216697039326',
    projectId: 'adhd-48cb5',
    authDomain: 'adhd-48cb5.firebaseapp.com',
    storageBucket: 'adhd-48cb5.firebasestorage.app',
    measurementId: 'G-ZXSQX9QWTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEC7vrv3Kzo40GPG5TFq0GNX1bagAatmg',
    appId: '1:216697039326:android:f308a4f9c6665c5f88554f',
    messagingSenderId: '216697039326',
    projectId: 'adhd-48cb5',
    storageBucket: 'adhd-48cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ex0H1puBuFwJX5RC8U9iT0jK0QdvtXM',
    appId: '1:216697039326:ios:072f42368d7eacc288554f',
    messagingSenderId: '216697039326',
    projectId: 'adhd-48cb5',
    storageBucket: 'adhd-48cb5.firebasestorage.app',
    iosBundleId: 'com.example.graduationAdhd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ex0H1puBuFwJX5RC8U9iT0jK0QdvtXM',
    appId: '1:216697039326:ios:072f42368d7eacc288554f',
    messagingSenderId: '216697039326',
    projectId: 'adhd-48cb5',
    storageBucket: 'adhd-48cb5.firebasestorage.app',
    iosBundleId: 'com.example.graduationAdhd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Q0LB31IXT5WUaVZszBsL2i3w5nKsz_8',
    appId: '1:216697039326:web:3181b6c80fb6ffee88554f',
    messagingSenderId: '216697039326',
    projectId: 'adhd-48cb5',
    authDomain: 'adhd-48cb5.firebaseapp.com',
    storageBucket: 'adhd-48cb5.firebasestorage.app',
    measurementId: 'G-4QE8CFQXX7',
  );
}
